/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Rockola extends javax.swing.JFrame {

    /**
     * Creates new form Rockola_form
     */
    public Rockola() {
        initComponents();
    }
    public static String ma1 = "--";
    public static String ma2 = "--";
    public static String ma3 = "--";
    public static String ma4 = "--";
    public static String ma5 = "--";
    public static ArrayList cancion = new ArrayList<>();
    String can1 = "";
    String can2 = "";
    String can3 = "";
    String can4 = "";
    String can5 = "";
    int artist = 0;
    int contador = 0;
    int h = 0;
    int m = 0;

//    public void musica(){
//        if(jcMusica1.isSelected()){
//            this.cancion.add(String.valueOf("pikachu"));
//            c++;
//            System.out.println(cancion);
//        }else{
//            this.cancion.remove(c);
//            c--;
//            System.out.println(cancion);
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        btnIngMoneda = new javax.swing.JButton();
        IngMoneda = new javax.swing.JTextField();
        Salir = new javax.swing.JButton();
        Reiniciar = new javax.swing.JButton();
        btnReproducir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        artista1 = new javax.swing.JButton();
        artista2 = new javax.swing.JButton();
        artista3 = new javax.swing.JButton();
        artista4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Album1 = new javax.swing.JPanel();
        album1 = new javax.swing.JLabel();
        Album2 = new javax.swing.JPanel();
        album2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jcMusica1 = new javax.swing.JCheckBox();
        jcMusica2 = new javax.swing.JCheckBox();
        jcMusica3 = new javax.swing.JCheckBox();
        jcMusica4 = new javax.swing.JCheckBox();
        jcMusica5 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        btnIngMoneda.setBackground(new java.awt.Color(51, 153, 0));
        btnIngMoneda.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        btnIngMoneda.setForeground(new java.awt.Color(255, 255, 255));
        btnIngMoneda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/coin_size64px.png"))); // NOI18N
        btnIngMoneda.setText("INSERTE MONEDA");
        btnIngMoneda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIngMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngMonedaActionPerformed(evt);
            }
        });

        IngMoneda.setBackground(new java.awt.Color(51, 153, 0));
        IngMoneda.setFont(new java.awt.Font("Unispace", 1, 40)); // NOI18N
        IngMoneda.setForeground(new java.awt.Color(255, 255, 255));
        IngMoneda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IngMoneda.setText("0");
        IngMoneda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Salir.setBackground(new java.awt.Color(255, 102, 102));
        Salir.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        Salir.setText("Salir");
        Salir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        Reiniciar.setBackground(new java.awt.Color(255, 153, 102));
        Reiniciar.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        Reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        Reiniciar.setText("Reiniciar");
        Reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReiniciarActionPerformed(evt);
            }
        });

        btnReproducir.setBackground(new java.awt.Color(0, 255, 0));
        btnReproducir.setFont(new java.awt.Font("Unispace", 1, 36)); // NOI18N
        btnReproducir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reproductor/play.png"))); // NOI18N
        btnReproducir.setText("Reproducir");
        btnReproducir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReproducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReproducirActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(12, 7, 7, 7, new java.awt.Color(255, 228, 63)));

        artista1.setBackground(new java.awt.Color(0, 0, 51));
        artista1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistas/BonJovi.png"))); // NOI18N
        artista1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(102, 153, 255)));
        artista1.setHideActionText(true);
        artista1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        artista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artista1ActionPerformed(evt);
            }
        });

        artista2.setBackground(new java.awt.Color(0, 0, 51));
        artista2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistas/Pokemon.png"))); // NOI18N
        artista2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 102, 102)));
        artista2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        artista2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artista2ActionPerformed(evt);
            }
        });

        artista3.setBackground(new java.awt.Color(0, 0, 51));
        artista3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistas/Metallica.png"))); // NOI18N
        artista3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 255, 255)));
        artista3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        artista3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artista3ActionPerformed(evt);
            }
        });

        artista4.setBackground(new java.awt.Color(0, 0, 51));
        artista4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistas/Shakira.png"))); // NOI18N
        artista4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 153, 255)));
        artista4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        artista4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artista4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Unispace", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("Elige tu Artista favorito:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(artista1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(artista2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(artista3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(artista4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(154, 154, 154))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(artista2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(artista1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(artista3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(artista4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/catcokla.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Gungsuh", 1, 72)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 228, 63));
        jLabel4.setText("CATCKOLA");

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 20, 5, 20, new java.awt.Color(255, 228, 63)));

        Album1.setBackground(new java.awt.Color(0, 0, 51));
        Album1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Album1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Album1MouseClicked(evt);
            }
        });

        album1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/albums/album#1.png"))); // NOI18N

        javax.swing.GroupLayout Album1Layout = new javax.swing.GroupLayout(Album1);
        Album1.setLayout(Album1Layout);
        Album1Layout.setHorizontalGroup(
            Album1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Album1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(album1)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        Album1Layout.setVerticalGroup(
            Album1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Album1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(album1)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        Album2.setBackground(new java.awt.Color(0, 0, 51));
        Album2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Album2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Album2MouseClicked(evt);
            }
        });

        album2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/albums/album#2.png"))); // NOI18N

        javax.swing.GroupLayout Album2Layout = new javax.swing.GroupLayout(Album2);
        Album2.setLayout(Album2Layout);
        Album2Layout.setHorizontalGroup(
            Album2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Album2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(album2)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        Album2Layout.setVerticalGroup(
            Album2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Album2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(album2)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Unispace", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 153));
        jLabel5.setText("ESCOGE");

        jLabel6.setFont(new java.awt.Font("Unispace", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 153));
        jLabel6.setText("UN ALBUM");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(Album1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(Album2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(17, 17, 17))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(41, 41, 41))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Album2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Album1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 3, 10, 3, new java.awt.Color(255, 228, 63)));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jcMusica1.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jcMusica1.setForeground(new java.awt.Color(102, 255, 102));
        jcMusica1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcMusica1MouseClicked(evt);
            }
        });

        jcMusica2.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jcMusica2.setForeground(new java.awt.Color(102, 255, 102));
        jcMusica2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcMusica2MouseClicked(evt);
            }
        });

        jcMusica3.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jcMusica3.setForeground(new java.awt.Color(102, 255, 102));
        jcMusica3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcMusica3MouseClicked(evt);
            }
        });

        jcMusica4.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jcMusica4.setForeground(new java.awt.Color(102, 255, 102));
        jcMusica4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcMusica4MouseClicked(evt);
            }
        });

        jcMusica5.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jcMusica5.setForeground(new java.awt.Color(102, 255, 102));
        jcMusica5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcMusica5MouseClicked(evt);
            }
        });
        jcMusica5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcMusica5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jcMusica1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jcMusica2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcMusica5)
                            .addComponent(jcMusica4)
                            .addComponent(jcMusica3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(233, 233, 233))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcMusica1)
                .addGap(11, 11, 11)
                .addComponent(jcMusica2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcMusica3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcMusica4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcMusica5)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(IngMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Reiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnIngMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnReproducir, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnIngMoneda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IngMoneda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Reiniciar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnReproducir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jcMusica1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcMusica1MouseClicked
        int c = 0;
        switch (artist) {
            case 1:
                if (h <= contador) {

                    if (jcMusica1.isSelected()) {
                        cancion.add(can1);
                        h++;
                    } else {
                        cancion.remove(c);
                    }
                }
                if (h >= contador) {
                    JOptionPane.showMessageDialog(null, "No se pueden agregar mas canciones");
                }
                break;
            case 2:
                if (h <= contador) {

                    if (jcMusica1.isSelected()) {
                        cancion.add(can1);
                        h++;
                    } else {
                        cancion.remove(c);
                    }
                }
                if (h >= contador) {
                    JOptionPane.showMessageDialog(null, "No se pueden agregar mas canciones");
                }
                break;
            case 3:
                if (h <= contador) {

                    if (jcMusica1.isSelected()) {
                        cancion.add(can1);
                        h++;
                    } else {
                        cancion.remove(c);
                    }
                }
                if (h >= contador) {
                    JOptionPane.showMessageDialog(null, "No se pueden agregar mas canciones");
                }
                break;
            case 4:
                if (h <= contador) {

                    if (jcMusica1.isSelected()) {
                        cancion.add(can1);
                        h++;
                    } else {
                        cancion.remove(c);
                    }
                }
                if (h >= contador) {
                    JOptionPane.showMessageDialog(null, "No se pueden agregar mas canciones");
                }
                break;
            case 5:
                if (h <= contador) {

                    if (jcMusica1.isSelected()) {
                        cancion.add(can1);
                        h++;
                    } else {
                        cancion.remove(c);
                    }
                }
                if (h >= contador) {
                    JOptionPane.showMessageDialog(null, "No se pueden agregar mas canciones");
                }
                break;
        }
    }//GEN-LAST:event_jcMusica1MouseClicked

    private void jcMusica2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcMusica2MouseClicked
        int c = 1;
        switch (artist) {
            case 1:
                if (h < contador) {

                    if (jcMusica2.isSelected()) {
                        cancion.add(can2);
                        System.out.println(can2);
                        h++;
                    } else {
                        cancion.remove(c);
                    }
                }
                if (h >= contador) {
                    JOptionPane.showMessageDialog(null, "No se pueden agregar mas canciones");
                }
                break;
            case 2:
                if (h < contador) {

                    if (jcMusica2.isSelected()) {
                        cancion.add(can2);
                        h++;
                    } else {
                        cancion.remove(c);
                    }
                }
                if (h >= contador) {
                    JOptionPane.showMessageDialog(null, "No se pueden agregar mas canciones");
                }
                break;
            case 3:
                if (h < contador) {

                    if (jcMusica2.isSelected()) {
                        cancion.add(can2);
                        h++;
                    } else {
                        cancion.remove(c);
                    }
                }
                if (h >= contador) {
                    JOptionPane.showMessageDialog(null, "No se pueden agregar mas canciones");
                }
                break;
            case 4:
                if (h < contador) {

                    if (jcMusica2.isSelected()) {
                        cancion.add(can2);
                        h++;
                    } else {
                        cancion.remove(c);
                    }
                }
                if (h >= contador) {
                    JOptionPane.showMessageDialog(null, "No se pueden agregar mas canciones");
                }
                break;
            case 5:
                if (h < contador) {

                    if (jcMusica2.isSelected()) {
                        cancion.add(can2);
                        h++;
                    } else {
                        cancion.remove(c);
                    }
                }
                if (h >= contador) {
                    JOptionPane.showMessageDialog(null, "No se pueden agregar mas canciones");
                }
                break;
        }
    }//GEN-LAST:event_jcMusica2MouseClicked

    private void jcMusica3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcMusica3MouseClicked

        int c = 2;
        switch (artist) {
            case 1:
                if (h < contador) {

                    if (jcMusica3.isSelected()) {
                        cancion.add(can3);
                        System.out.println(can3);
                        h++;
                    } else {
                        cancion.remove(c);
                    }
                }
                if (h >= contador) {
                    JOptionPane.showMessageDialog(null, "No se pueden agregar mas canciones");
                }
                break;
            case 2:
                if (h < contador) {

                    if (jcMusica3.isSelected()) {
                        cancion.add(can3);
                        h++;
                    } else {
                        cancion.remove(c);
                    }
                }
                if (h >= contador) {
                    JOptionPane.showMessageDialog(null, "No se pueden agregar mas canciones");
                }
                break;
            case 3:
                if (h < contador) {

                    if (jcMusica3.isSelected()) {
                        cancion.add(can3);
                        h++;
                    } else {
                        cancion.remove(c);
                    }
                }
                if (h >= contador) {
                    JOptionPane.showMessageDialog(null, "No se pueden agregar mas canciones");
                }
                break;
            case 4:
                if (h < contador) {

                    if (jcMusica3.isSelected()) {
                        cancion.add(can3);
                        h++;
                    } else {
                        cancion.remove(c);
                    }
                }
                if (h >= contador) {
                    JOptionPane.showMessageDialog(null, "No se pueden agregar mas canciones");
                }
                break;
            case 5:
                if (h < contador) {

                    if (jcMusica3.isSelected()) {
                        cancion.add(can3);
                        h++;
                    } else {
                        cancion.remove(c);
                    }
                }
                if (h >= contador) {
                    JOptionPane.showMessageDialog(null, "No se pueden agregar mas canciones");
                }
                break;
        }
    }//GEN-LAST:event_jcMusica3MouseClicked

    private void jcMusica4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcMusica4MouseClicked
        int c = 3;
        switch (artist) {
            case 1:
                if (h < contador) {

                    if (jcMusica4.isSelected()) {
                        cancion.add(can4);
                        System.out.println(can4);
                        h++;
                    } else {
                        cancion.remove(c);
                    }
                }
                if (h >= contador) {
                    JOptionPane.showMessageDialog(null, "No se pueden agregar mas canciones");
                }
                break;
            case 2:
                if (h < contador) {

                    if (jcMusica4.isSelected()) {
                        cancion.add(can4);
                        h++;
                    } else {
                        cancion.remove(c);
                    }
                }
                if (h >= contador) {
                    JOptionPane.showMessageDialog(null, "No se pueden agregar mas canciones");
                }
                break;
            case 3:
                if (h < contador) {

                    if (jcMusica4.isSelected()) {
                        cancion.add(can4);
                        h++;
                    } else {
                        cancion.remove(c);
                    }
                }
                if (h >= contador) {
                    JOptionPane.showMessageDialog(null, "No se pueden agregar mas canciones");
                }
                break;
            case 4:
                if (h < contador) {

                    if (jcMusica4.isSelected()) {
                        cancion.add(can4);
                        h++;
                    } else {
                        cancion.remove(c);
                    }
                }
                if (h >= contador) {
                    JOptionPane.showMessageDialog(null, "No se pueden agregar mas canciones");
                }
                break;
            case 5:
                if (h < contador) {
                    if (jcMusica4.isSelected()) {
                        cancion.add(can4);
                        h++;
                    } else {
                        cancion.remove(c);
                    }
                }
                if (h >= contador) {
                    JOptionPane.showMessageDialog(null, "No se pueden agregar mas canciones");
                }
                break;
        }
    }//GEN-LAST:event_jcMusica4MouseClicked

    private void jcMusica5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcMusica5MouseClicked
        int c = 4;

        switch (artist) {
            case 1:
                if (h < contador) {

                    if (jcMusica5.isSelected()) {
                        cancion.add(can5);
                        h++;
                    } else {
                        cancion.remove(c);
                    }
                }
                if (h >= contador) {
                    JOptionPane.showMessageDialog(null, "No se pueden agregar mas canciones");
                }
                break;
            case 2:
                if (h < contador) {

                    if (jcMusica5.isSelected()) {
                        cancion.add(can5);
                        h++;
                    } else {
                        cancion.remove(c);
                    }
                }
                if (h >= contador) {
                    JOptionPane.showMessageDialog(null, "No se pueden agregar mas canciones");
                }
                break;
            case 3:
                if (h < contador) {

                    if (jcMusica5.isSelected()) {
                        cancion.add(can5);
                        h++;
                    } else {
                        cancion.remove(c);
                    }
                }
                if (h >= contador) {
                    JOptionPane.showMessageDialog(null, "No se pueden agregar mas canciones");
                }
                break;
            case 4:
                if (h < contador) {

                    if (jcMusica5.isSelected()) {
                        cancion.add(can5);
                        h++;
                    } else {
                        cancion.remove(c);
                    }
                }
                if (h >= contador) {
                    JOptionPane.showMessageDialog(null, "No se pueden agregar mas canciones");
                }
                break;
            case 5:
                if (h < contador) {

                    if (jcMusica5.isSelected()) {
                        cancion.add(can5);
                        h++;
                    } else {
                        cancion.remove(c);
                    }
                }
                if (h >= contador) {
                    JOptionPane.showMessageDialog(null, "No se pueden agregar mas canciones");
                }
                break;
        }
    }//GEN-LAST:event_jcMusica5MouseClicked

    private void artista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artista1ActionPerformed
//        int artist = 1;
//        bon.setArtista(artist);
//        bon.EligeArtista(m);
        artist = 1;
        this.jcMusica1.setSelected(false);
        this.jcMusica2.setSelected(false);
        this.jcMusica3.setSelected(false);
        this.jcMusica4.setSelected(false);
        this.jcMusica5.setSelected(false);
    }//GEN-LAST:event_artista1ActionPerformed

    private void artista2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artista2ActionPerformed
//        int artist = 2;
//        bon.setArtista(artist);
//        bon.EligeArtista(m);
        artist = 2;
        this.jcMusica1.setSelected(false);
        this.jcMusica2.setSelected(false);
        this.jcMusica3.setSelected(false);
        this.jcMusica4.setSelected(false);
        this.jcMusica5.setSelected(false);
    }//GEN-LAST:event_artista2ActionPerformed

    private void artista3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artista3ActionPerformed
//        int artist = 3;
//        bon.setArtista(artist);
//        bon.EligeArtista(m);
        artist = 3;
        this.jcMusica1.setSelected(false);
        this.jcMusica2.setSelected(false);
        this.jcMusica3.setSelected(false);
        this.jcMusica4.setSelected(false);
        this.jcMusica5.setSelected(false);
    }//GEN-LAST:event_artista3ActionPerformed

    private void Album1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Album1MouseClicked
//        switch (bon.getArtista()) {
        switch (artist) {
            case 1:
                can1 = "A1BonJoviM1";
                can2 = "A1BonJoviM2";
                can3 = "A1BonJoviM3";
                can4 = "A1BonJoviM4";
                can5 = "A1BonJoviM5";
                this.jcMusica1.setText("A1BonJoviM1");
                this.jcMusica2.setText("A1BonJoviM2");
                this.jcMusica3.setText("A1BonJoviM3");
                this.jcMusica4.setText("A1BonJoviM4");
                this.jcMusica5.setText("A1BonJoviM5");
                break;
            case 2:
                can1 = "A1PokemonM1";
                can2 = "A1PokemonM2";
                can3 = "A1PokemonM3";
                can4 = "A1PokemonM4";
                can5 = "A1PokemonM5";
                this.jcMusica1.setText("A1PokemonM1");
                this.jcMusica2.setText("A1PokemonM2");
                this.jcMusica3.setText("A1PokemonM3");
                this.jcMusica4.setText("A1PokemonM4");
                this.jcMusica5.setText("A1PokemonM5");
                break;
            case 3:
                can1 = "A1MetallicaM1";
                can2 = "A1MetallicaM2";
                can3 = "A1MetallicaM3";
                can4 = "A1MetallicaM4";
                can5 = "A1MetallicaM5";
                this.jcMusica1.setText("A1MetallicaM1");
                this.jcMusica2.setText("A1MetallicaM2");
                this.jcMusica3.setText("A1MetallicaM3");
                this.jcMusica4.setText("A1MetallicaM4");
                this.jcMusica5.setText("A1MetallicaM5");
                break;
            case 4:
                can1 = "A1ShakiraM1";
                can2 = "A1ShakiraM2";
                can3 = "A1ShakiraM3";
                can4 = "A1ShakiraM4";
                can5 = "A1ShakiraM5";
                this.jcMusica1.setText("A1ShakiraM1");
                this.jcMusica2.setText("A1ShakiraM2");
                this.jcMusica3.setText("A1ShakiraM3");
                this.jcMusica4.setText("A1ShakiraM4");
                this.jcMusica5.setText("A1ShakiraM5");
                break;
        }
    }//GEN-LAST:event_Album1MouseClicked

    private void Album2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Album2MouseClicked

        switch (artist) {
            case 1:
                can1 = "A2BonJoviM1";
                can2 = "A2BonJoviM2";
                can3 = "A2BonJoviM3";
                can4 = "A2BonJoviM4";
                can5 = "A2BonJoviM5";
                this.jcMusica1.setText("A2BonJoviM1");
                this.jcMusica2.setText("A2BonJoviM2");
                this.jcMusica3.setText("A2BonJoviM3");
                this.jcMusica4.setText("A2BonJoviM4");
                this.jcMusica5.setText("A2BonJoviM5");
                break;
            case 2:
                can1 = "A2PokemonM1";
                can2 = "A2PokemonM2";
                can3 = "A2PokemonM3";
                can4 = "A2PokemonM4";
                can5 = "A2PokemonM5";
                this.jcMusica1.setText("A2PokemonM1");
                this.jcMusica2.setText("A2PokemonM2");
                this.jcMusica3.setText("A2PokemonM3");
                this.jcMusica4.setText("A2PokemonM4");
                this.jcMusica5.setText("A2PokemonM5");
                break;
            case 3:
                can1 = "A2MetallicaM1";
                can2 = "A2MetallicaM2";
                can3 = "A2MetallicaM3";
                can4 = "A2MetallicaM4";
                can5 = "A2MetallicaM5";
                this.jcMusica1.setText("A2MetallicaM1");
                this.jcMusica2.setText("A2MetallicaM2");
                this.jcMusica3.setText("A2MetallicaM3");
                this.jcMusica4.setText("A2MetallicaM4");
                this.jcMusica5.setText("A2MetallicaM5");
                break;
            case 4:
                can1 = "A2ShakiraM1";
                can2 = "A2ShakiraM2";
                can3 = "A2ShakiraM3";
                can4 = "A2ShakiraM4";
                can5 = "A2ShakiraM5";
                this.jcMusica1.setText("A2ShakiraM1");
                this.jcMusica2.setText("A2ShakiraM2");
                this.jcMusica3.setText("A2ShakiraM3");
                this.jcMusica4.setText("A2ShakiraM4");
                this.jcMusica5.setText("A2ShakiraM5");
                break;
        }
    }//GEN-LAST:event_Album2MouseClicked

    private void btnIngMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngMonedaActionPerformed

        m = Integer.parseInt(this.IngMoneda.getText());

        if (m == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar almenos 1 moneda");
            m = 0;
        } else if (m > 0) {
            if (m <= 5) {
                JOptionPane.showMessageDialog(null, "Puedes elegir " + m + " canciones");
                this.IngMoneda.setEnabled(false);
                contador = m;
            } else if (m > 5) {
                JOptionPane.showMessageDialog(null, "No puedes ingresar mas de 5 monedas");
                m = 0;
            }

        }
//        bon.setMoneda(m);

//        int m = Integer.parseInt(JOptionPane.showInputDialog("Ingrese Cuantas monedas desee ingresar", 0));
//
//        try {
//            if (m == 0) {
//                JOptionPane.showMessageDialog(null, "Debes ingresar almenos 1 moneda");
//
//            } else if (m > 0) {
//                if (m <= 5) {
//                    JOptionPane.showMessageDialog(null, "Puedes elegir " + m + " canciones");
//                } else if (m > 5) {
//                    JOptionPane.showMessageDialog(null, "No puedes ingresar mas de 5");
//                }
//            }
//        } catch (NumberFormatException aa) {
//        } finally {
//            JOptionPane.showInputDialog("Ingrese Cuantas monedas desee ingresar", 0);
//        }System.out.println(m);
//        try{
//        int a =Integer.parseInt(JOptionPane.showInputDialog("a"));
//           if(a==0){
//            JOptionPane.showMessageDialog(this,"El año es bisiesto");
//           }else{
//               JOptionPane.showMessageDialog(this, "El año no es bisiesto");
//           }
//         }catch(NumberFormatException aea){
//         JOptionPane.showMessageDialog(this,"NO debes dejar el espacio vacio");
//         }int resp =JOptionPane.showConfirmDialog(null, "TERMINO DE REGISTRARSE",
//                "SELECCIONE", JOptionPane.YES_NO_CANCEL_OPTION,
//                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnIngMonedaActionPerformed

    private void ReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReiniciarActionPerformed
        this.IngMoneda.setText("0");
        this.IngMoneda.setEnabled(true);
        this.jcMusica1.setSelected(false);
        this.jcMusica2.setSelected(false);
        this.jcMusica3.setSelected(false);
        this.jcMusica4.setSelected(false);
        this.jcMusica5.setSelected(false);
        contador = 0;
        this.cancion.clear();

    }//GEN-LAST:event_ReiniciarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void artista4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artista4ActionPerformed
//        int artist = 4;
//        bon.setArtista(artist);
//        bon.EligeArtista(m);
        artist = 4;
        this.jcMusica1.setSelected(false);
        this.jcMusica2.setSelected(false);
        this.jcMusica3.setSelected(false);
        this.jcMusica4.setSelected(false);
        this.jcMusica5.setSelected(false);
    }//GEN-LAST:event_artista4ActionPerformed

    private void btnReproducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReproducirActionPerformed
//        int e = Integer.parseInt(JOptionPane.showInputDialog(null, "que cancione desea borrar?"));
//        int i;
//
//        for (i = 0; i < cancion.size(); i++) {
//
//            if ("a" == this.cancion.get(i)) {
//        this.cancion.remove(e);
//                break;
//
//            }
//
//        }

        repro rep = new repro();
        rep.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnReproducirActionPerformed

    private void jcMusica5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcMusica5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcMusica5ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rockola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rockola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rockola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rockola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rockola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Album1;
    private javax.swing.JPanel Album2;
    private javax.swing.JTextField IngMoneda;
    private javax.swing.JButton Reiniciar;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel album1;
    private javax.swing.JLabel album2;
    private javax.swing.JButton artista1;
    private javax.swing.JButton artista2;
    private javax.swing.JButton artista3;
    private javax.swing.JButton artista4;
    private javax.swing.JButton btnIngMoneda;
    private javax.swing.JButton btnReproducir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JCheckBox jcMusica1;
    private javax.swing.JCheckBox jcMusica2;
    private javax.swing.JCheckBox jcMusica3;
    private javax.swing.JCheckBox jcMusica4;
    private javax.swing.JCheckBox jcMusica5;
    // End of variables declaration//GEN-END:variables

}
